name: Snapshot to Maven Central Repository
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[maven-release-plugin]') }}
    steps:
      - uses: actions/checkout@v6
      - name: Determine Java version from POM
        run: |
          echo "JAVA_VERSION=$(mvn initialize help:evaluate -Dexpression=jdk.version -q -DforceStdout)" >> ${GITHUB_ENV}

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build, test, verify
        run: mvn -B verify -DskipFlatten

        # Running setup-java again overwrites the settings.xml - IT'S MANDATORY TO DO THIS SECOND SETUP!!!
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish snapshot
        run: mvn deploy -DskipUT -DskipIT
        env:
          MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}
